schema_version: 1

context:
  name: zemaxglass
  version: "2.0.1"
  python_min: "3.12"
  build_number: 1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d59368c855f1548c6b6ff954dc2e3254ca4a9d9fe5260616df64ccfd846d7040

build:
  number: ${{ build_number }}
  noarch: python
  script:
    - echo 'recursive-include src *.agf *.AGF' > MANIFEST.in
    - ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - zemaxglassdemo = ZemaxGlass.ZemaxGlass:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=83.0.0
    - setuptools-scm >=10.2.1
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.4.6
    - scipy >=1.17.1
    - matplotlib-base >=3.10.9
    - cycler >=0.12.1

tests:
  - python:
      imports:
        - ZemaxGlass
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - package_contents:
      site_packages:
        - ZemaxGlass/**
        - ZemaxGlass/AGF_files/archer.agf
        - ZemaxGlass/AGF_files/*.agf
        - zemaxglass-${{ version }}.dist-info/**
      strict: true

about:
  summary: Zemax glass (.agf) file reader
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/nzhagen/zemaxglass
  documentation: https://github.com/nzhagen/zemaxglass/ZemaxGlass_user_manual.pdf

extra:
  recipe-maintainers:
    - mjhoptics
